/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef client_CONSTANTS_H
#define client_CONSTANTS_H

#include "client_types.h"

namespace accumulo { namespace client {

class clientConstants {
 public:
  clientConstants();

};

extern const clientConstants g_client_constants;

}} // namespace

#endif
