/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef cloudtrace_CONSTANTS_H
#define cloudtrace_CONSTANTS_H

#include "cloudtrace_types.h"

namespace accumulo { namespace cloudtrace {

class cloudtraceConstants {
 public:
  cloudtraceConstants();

};

extern const cloudtraceConstants g_cloudtrace_constants;

}} // namespace

#endif
