/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef data_CONSTANTS_H
#define data_CONSTANTS_H

#include "data_types.h"

namespace accumulo { namespace data {

class dataConstants {
 public:
  dataConstants();

};

extern const dataConstants g_data_constants;

}} // namespace

#endif
