/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef gc_CONSTANTS_H
#define gc_CONSTANTS_H

#include "gc_types.h"

namespace accumulo { namespace gc {

class gcConstants {
 public:
  gcConstants();

};

extern const gcConstants g_gc_constants;

}} // namespace

#endif
