/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "gc_constants.h"

namespace accumulo { namespace gc {

const gcConstants g_gc_constants;

gcConstants::gcConstants() {
}

}} // namespace

