/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "security_constants.h"

namespace accumulo { namespace security {

const securityConstants g_security_constants;

securityConstants::securityConstants() {
}

}} // namespace

