/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef tabletserver_CONSTANTS_H
#define tabletserver_CONSTANTS_H

#include "tabletserver_types.h"

namespace accumulo { namespace tabletserver {

class tabletserverConstants {
 public:
  tabletserverConstants();

};

extern const tabletserverConstants g_tabletserver_constants;

}} // namespace

#endif
