/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef TestService_H
#define TestService_H

#include <TProcessor.h>
#include "cloudtrace_types.h"

namespace accumulo { namespace cloudtrace {

class TestServiceIf {
 public:
  virtual ~TestServiceIf() {}
  virtual bool checkTrace(const TInfo& tinfo, const std::string& message) = 0;
};

class TestServiceNull : virtual public TestServiceIf {
 public:
  virtual ~TestServiceNull() {}
  bool checkTrace(const TInfo& /* tinfo */, const std::string& /* message */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _TestService_checkTrace_args__isset {
  _TestService_checkTrace_args__isset() : tinfo(false), message(false) {}
  bool tinfo;
  bool message;
} _TestService_checkTrace_args__isset;

class TestService_checkTrace_args {
 public:

  TestService_checkTrace_args() : message("") {
  }

  virtual ~TestService_checkTrace_args() throw() {}

  TInfo tinfo;
  std::string message;

  _TestService_checkTrace_args__isset __isset;

  bool operator == (const TestService_checkTrace_args & rhs) const
  {
    if (!(tinfo == rhs.tinfo))
      return false;
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const TestService_checkTrace_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestService_checkTrace_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TestService_checkTrace_pargs {
 public:


  virtual ~TestService_checkTrace_pargs() throw() {}

  const TInfo* tinfo;
  const std::string* message;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TestService_checkTrace_result__isset {
  _TestService_checkTrace_result__isset() : success(false) {}
  bool success;
} _TestService_checkTrace_result__isset;

class TestService_checkTrace_result {
 public:

  TestService_checkTrace_result() : success(0) {
  }

  virtual ~TestService_checkTrace_result() throw() {}

  bool success;

  _TestService_checkTrace_result__isset __isset;

  bool operator == (const TestService_checkTrace_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TestService_checkTrace_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestService_checkTrace_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TestService_checkTrace_presult__isset {
  _TestService_checkTrace_presult__isset() : success(false) {}
  bool success;
} _TestService_checkTrace_presult__isset;

class TestService_checkTrace_presult {
 public:


  virtual ~TestService_checkTrace_presult() throw() {}

  bool* success;

  _TestService_checkTrace_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TestServiceClient : virtual public TestServiceIf {
 public:
  TestServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  TestServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool checkTrace(const TInfo& tinfo, const std::string& message);
  void send_checkTrace(const TInfo& tinfo, const std::string& message);
  bool recv_checkTrace();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TestServiceProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<TestServiceIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (TestServiceProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_checkTrace(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TestServiceProcessor(boost::shared_ptr<TestServiceIf> iface) :
    iface_(iface) {
    processMap_["checkTrace"] = &TestServiceProcessor::process_checkTrace;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~TestServiceProcessor() {}
};

class TestServiceMultiface : virtual public TestServiceIf {
 public:
  TestServiceMultiface(std::vector<boost::shared_ptr<TestServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TestServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TestServiceIf> > ifaces_;
  TestServiceMultiface() {}
  void add(boost::shared_ptr<TestServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool checkTrace(const TInfo& tinfo, const std::string& message) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->checkTrace(tinfo, message);
      } else {
        ifaces_[i]->checkTrace(tinfo, message);
      }
    }
  }

};

}} // namespace

#endif
